title: <p align="center"> T.S.Prabakaran </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/prabakaran-ts-034377288/">LinkedIn</a> |
  <a href="https://github.com/PrabakarTS">GitHub</a>
  
  <br>   
  I'm learning Executive PG Programme in Machine Learning.
  <br>
  </p>



theme: jekyll-theme-minimal